#ifndef __KL_LANGUAGE_H__
#define __KL_LANGUAGE_H__

#include "pch.h"

#include <string>
#include <mutex>
#include <unordered_map>

enum KLLangType
{
	KLL_TYPE_SIMPLE_CHINESE,
	KLL_TYPE_ENGLISH,

	KLL_TYPE_MAXIMUM,
};

enum KLLangTextKey
{
	KLL_KEY_NONE,

	KLL_KEY_GLOBAL = 1,
	KLL_KEY_DEVICE_INFO,
	KLL_KEY_LANGUAGE,
	KLL_KEY_STARTUP,
	KLL_KEY_EXIT,
	KLL_KEY_SLEEP,
	KLL_KEY_RESET,
	KLL_KEY_DEVICE_MODEL,
	KLL_KEY_CHIP_MODEL,
	KLL_KEY_HARDWARE_VERSION,
	KLL_KEY_SOFTWARE_VERSION,
	KLL_KEY_AUTO_RUN,
	KLL_KEY_WHEN_CLICK_X,
	KLL_KEY_DIRECT_EXIT,
	KLL_KEY_RESIDES_SYSTEM_TRAY,
	KLL_KEY_MINUTE,
	KLL_KEY_SECOND,
	KLL_KEY_TOOLTIP_SLEEP,
	KLL_KEY_RESET_BTN,
	KLL_KEY_RESTORE_FACTORY_SETTINGS,
	KLL_KEY_KEY_ASSIGNMENT,
	KLL_KEY_LIGHT_EFFECT,
	KLL_KEY_EFFECT,
	KLL_KEY_MACRO_EDIT,
	KLL_KEY_PROFILE,
	KLL_KEY_IMPORT,
	KLL_KEY_EXPORT,
	KLL_KEY_RENAME,
	KLL_KEY_DELETE,
	KLL_KEY_NEW,
	KLL_KEY_PREVIEW,
	KLL_KEY_WAIT_FOR_CONNECTION,
	KLL_KEY_DEVICE_CONNECTED,
	
	KLL_KEY_DEVICE_SETTINGS,
	KLL_KEY_PROGRAM_SETTINGS,
	KLL_KEY_LOOP_UNTIL_KEYUP,
	KLL_KEY_LOOP_UNTIL_KEYDOWN,
	KLL_KEY_LOOP_SPECIFY_COUNT,
	KLL_KEY_SUCCESSFUL,
	KLL_KEY_FAILED,
	KLL_KEY_OK,
	KLL_KEY_CANCEL,
	KLL_KEY_DEVICE_NOT_CONNECTED,
	KLL_KEY_TRIGGER_MODE,
	KLL_KEY_LOOP_COUNT,
	KLL_KEY_RECORDER,
	KLL_KEY_SAVE,
	KLL_KEY_FUNCTION_KEY,
	KLL_KEY_MACRO,
	KLL_KEY_DEFAULT,
	KLL_KEY_CURRENT,
	KLL_KEY_LAYER_DEFAULT,
	KLL_KEY_LAYER_FN1,
	KLL_KEY_LAYER_FN2,
	KLL_KEY_LIGHT_SETTINGS,

	KLL_KEY_LIGHT_1 = 80,
	KLL_KEY_LIGHT_2,
	KLL_KEY_LIGHT_3,
	KLL_KEY_LIGHT_4,
	KLL_KEY_LIGHT_5,
	KLL_KEY_LIGHT_6,
	KLL_KEY_LIGHT_7,
	KLL_KEY_LIGHT_8,
	KLL_KEY_LIGHT_9,
	KLL_KEY_LIGHT_10,
	KLL_KEY_LIGHT_11,
	KLL_KEY_LIGHT_12,
	KLL_KEY_LIGHT_13,
	KLL_KEY_LIGHT_14,
	KLL_KEY_LIGHT_15,
	KLL_KEY_LIGHT_16,


	KLL_KEY_SEQ_BEGIN_MS = 100,
	KLL_KEY_SEQ_END_MS,
	KLL_KEY_SEQ_RECORD_START,
	KLL_KEY_SEQ_RECORD_STOP,
	KLL_KEY_SEQ_RECORD_SAVE,

	KLL_KEY_DIALOG_MSG = 120,

	KLL_KEY_DIALOG_DEL_CONFIG = 130,
	KLL_KEY_DIALOG_DEL_CONFIG_CONFIRM,
	KLL_KEY_DIALOG_NEW_CONFIG,
	KLL_KEY_DIALOG_REN_CONFIG,
	KLL_KEY_DIALOG_NEW_ERROR_CONFIG_EXISTSED,
	KLL_KEY_DIALOG_REN_ERROR_CONFIG_EXISTSED,
	KLL_KEY_DIALOG_DEL_ERROR_KEEP_AT_LEAST_ONE,

	KLL_KEY_MAXIMUM,
};

class KLLanguageManager
{
public:
	KLLangType currentType;
	std::unordered_map<KLLangType, std::unordered_map<KLLangTextKey, std::string>> map;

	void LoadConfig(const char* filename = LANGUAGE_FILE_NAME);

	void SetLanguage(KLLangType type)
	{
		currentType = type;
	}
	KLLangType GetLanguage()
	{
		return currentType;
	}

	std::string Text(KLLangTextKey key)
	{
		return map[currentType][key];
	}

public:
	static KLLanguageManager* GetInstance()
	{
		std::call_once(s_OnceFlag, []() {
			s_Instance = new KLLanguageManager();
			});
		return s_Instance;
	}
private:
	KLLanguageManager() : currentType(KLL_TYPE_SIMPLE_CHINESE) {}
private:
	static std::once_flag     s_OnceFlag;
	static KLLanguageManager* s_Instance;
};


#define KLLABLEB(key, id) (KLLanguageManager::GetInstance()->Text(key) + "##" + (id)).c_str()
#define KLLABLEA(key) (KLLanguageManager::GetInstance()->Text(key)).c_str()

#endif